# Generated by Django 3.1.5 on 2022-11-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kategorimodel',
            table='kategori',
        ),
    ]
