# Generated by Django 3.1.5 on 2022-11-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_yazilarmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazilarmodel',
            name='resim',
            field=models.ImageField(null=True, upload_to='yazi_resimleri'),
        ),
    ]
